"""add users and nullable ownership

Revision ID: 35cdd577edbd
Revises: eb2d388a4f40
Create Date: 2026-09-23 01:25:32.360309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect


# revision identifiers, used by Alembic.
revision: str = '35cdd577edbd'
down_revision: Union[str, Sequence[str], None] = 'eb2d388a4f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('assistant_conversations', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'assistant_conversations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('history_items', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'history_items', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def _drop_user_id_fk(table_name: str) -> None:
    """Drop the user_id foreign key using its database-assigned name."""
    bind = op.get_bind()
    for foreign_key in sa_inspect(bind).get_foreign_keys(table_name):
        if foreign_key["constrained_columns"] == ["user_id"]:
            op.drop_constraint(foreign_key["name"], table_name, type_="foreignkey")


def downgrade() -> None:
    """Downgrade schema."""
    _drop_user_id_fk("history_items")
    op.drop_column("history_items", "user_id")
    _drop_user_id_fk("documents")
    op.drop_column("documents", "user_id")
    _drop_user_id_fk("assistant_conversations")
    op.drop_column("assistant_conversations", "user_id")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
