"""persist validated assistant message references

Revision ID: ef0bf391ed04
Revises: 35cdd577edbd
Create Date: 2026-09-23 12:40:20.008309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0bf391ed04'
down_revision: Union[str, Sequence[str], None] = '35cdd577edbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_message_references',
    sa.Column('message_id', sa.String(length=160), nullable=False),
    sa.Column('research_record_id', sa.String(length=160), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('citation_label', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('prototype', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['assistant_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_record_id'], ['research_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('message_id', 'research_record_id')
    )
    op.create_index(op.f('ix_assistant_message_references_research_record_id'), 'assistant_message_references', ['research_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_message_references_research_record_id'), table_name='assistant_message_references')
    op.drop_table('assistant_message_references')
    # ### end Alembic commands ###
